kind: Service
apiVersion: v1
metadata:
  name: docker-registry
  namespace: {{ .Values.namespace }}
  labels:
    app: docker-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
  - name: http
    port: 30000
    nodePort: 30000