apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-nosqlbench-cassdiff-{{ .Release.Revision }}
spec:
  entrypoint: execute
  serviceAccountName: argo
  templates:
  - name: execute
    dag:
      tasks:
      - name: cassandra-ready
        templateRef:                  
          name: cassandra-status
          template: ready
      - name: start-registry
        templateRef:                  
          name: registry
          template: registry-template
      - name: build-spark
        depends: "start-registry"
        arguments:
          parameters:
          - name: registry_ip
            value: "{{`{{tasks.start-registry.ip}}`}}"
        templateRef:
          name: spark-image
          template: spark-image-template
      - name: nosqlbench-source
        depends: "cassandra-ready"
        templateRef:
          name: nosqlbench-job
          template: nosqlbench-source
      - name: nosqlbench-target
        depends: "cassandra-ready"
        templateRef:
          name: nosqlbench-job
          template: nosqlbench-target
      - name: run-diff
        depends: "build-spark && nosqlbench-source && nosqlbench-target"
        arguments:
          parameters:
          - name: registry_ip
            value: "{{`{{tasks.start-registry.ip}}`}}"
        templateRef:
          name: spark-job
          template: spark-job-template