apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cassandra-image
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  templates:
  - name: cassandra-image-template
    inputs:
      parameters:
      - name: git_identifier
    container:
      image: gcr.io/kaniko-project/executor:v1.6.0-debug
      command:
        - sh
        - -c
      args:
        - until `wget --spider http://localhost:30000`; do echo sleep && sleep 1; done;
          /kaniko/executor --dockerfile=/dockerfile/Dockerfile
          --context=dir:///workspace
          --destination=localhost:30000/adelphi/cassandra
          --insecure=true;
      volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: dockerfile
          mountPath: /dockerfile
    sidecars:
    - name : nginx
      image: nginx
      ports:
        - containerPort: 30000
          hostPort: 30000
          protocol: TCP
      volumeMounts:
      - name: proxy-config
        mountPath: /etc/nginx/conf.d
    initContainers:
    - name: clone-cassandra
      image: alpine/git
      workingDir: /download
      command:
        - sh
        - -c
      args:
        - git clone https://github.com/apache/cassandra.git cassandra;
          cd cassandra;
          git checkout {{`{{inputs.parameters.git_identifier}}`}};
      volumeMounts:
      - name: download
        mountPath: /download
    - name: build-cassandra
      image: openjdk:11
      command:
        - sh
        - -c
      args:
        - wget -O - https://downloads.apache.org/ant/binaries/apache-ant-1.10.11-bin.tar.gz | tar -zxvf -;
          chmod +x /apache-ant-1.10.11/bin/ant;
          ln -s /apache-ant-1.10.11/bin/ant /usr/bin/ant;
          cd /download/cassandra;
          ant artifacts -Duse.jdk11=true -Dant.gen-doc.skip=true -Dno-javadoc=true;
          mkdir /workspace/cassandra;
          tar -zxvf ./build/apache-cassandra-*-bin.tar.gz --strip-components=1 -C /workspace/cassandra;
          cp /dockerfile/docker-entrypoint.sh /workspace; 
      volumeMounts:
      - name: download
        mountPath: /download
      - name: workspace
        mountPath: /workspace
      - name: dockerfile
        mountPath: /dockerfile
    volumes:
    - name: workspace
      emptyDir: {}
    - name: download
      emptyDir: {}
    - name: dockerfile
      configMap:
        name: cassandra-dockerfile-configmap
    - name: proxy-config
      configMap:
        name: registry-proxy-configmap
