apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cassandra-clusters
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  templates:
  - name: start-source-cluster
    resource:
      action: create
      manifest: |
        apiVersion: cassandra.datastax.com/v1beta1
        kind: CassandraDatacenter
        metadata:
          name: {{ .Values.source.dc }}
          namespace: {{ .Values.namespace }}
          ownerReferences:
          - apiVersion: argoproj.io/v1alpha1
            blockOwnerDeletion: true
            kind: Workflow
            name: "{{`{{workflow.name}}`}}"
            uid: "{{`{{workflow.uid}}`}}"
        spec:
          allowMultipleNodesPerWorker: {{ .Values.allowMultipleNodesPerWorker }}
          clusterName: {{ .Values.source.clusterName }}
          serverType: cassandra
          serverVersion: {{ .Values.source.version }}
          managementApiAuth:
            insecure: {}
          # Limit each pod to a fixed 1 CPU cores and 2 GB of RAM.
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 2Gi
              cpu: 1000m
          size: {{ .Values.clusterSize }}
          storageConfig:
            cassandraDataVolumeClaimSpec:
              storageClassName: {{ .Values.storageClassName }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
          config:    
            cassandra-yaml:
              authenticator: org.apache.cassandra.auth.PasswordAuthenticator
              authorizer: org.apache.cassandra.auth.CassandraAuthorizer
              role_manager: org.apache.cassandra.auth.CassandraRoleManager
            jvm-options:
              initial_heap_size: "800M"
              max_heap_size: "800M"
  - name: start-target-cluster
    resource:
      action: create
      manifest: |
        apiVersion: cassandra.datastax.com/v1beta1
        kind: CassandraDatacenter
        metadata:
          name: {{ .Values.target.dc }}
          namespace: {{ .Values.namespace }}
          ownerReferences:
          - apiVersion: argoproj.io/v1alpha1
            blockOwnerDeletion: true
            kind: Workflow
            name: "{{`{{workflow.name}}`}}"
            uid: "{{`{{workflow.uid}}`}}"
        spec:
          allowMultipleNodesPerWorker: {{ .Values.allowMultipleNodesPerWorker }}
          clusterName: {{ .Values.target.clusterName }}
          serverType: cassandra
          serverVersion: {{ .Values.target.version }}
          managementApiAuth:
            insecure: {}
          # Limit each pod to a fixed 1 CPU cores and 2 GB of RAM.
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 2Gi
              cpu: 1000m
          size: {{ .Values.clusterSize }}
          storageConfig:
            cassandraDataVolumeClaimSpec:
              storageClassName: {{ .Values.storageClassName }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
          config:    
            cassandra-yaml:
              authenticator: org.apache.cassandra.auth.PasswordAuthenticator
              authorizer: org.apache.cassandra.auth.CassandraAuthorizer
              role_manager: org.apache.cassandra.auth.CassandraRoleManager
            jvm-options:
              initial_heap_size: "800M"
              max_heap_size: "800M"