apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-diff-configmap
  namespace: {{ .Values.namespace }}
data:
  collect.sh: |
    #!/bin/sh
    # Read the cassandra-diff tables and store the results in the shared volume
    mkdir /results/cassandra-diff
    collect() {
      table="$1";
      kubectl exec -n {{ .Values.namespace }} -i -t -c cassandra \
      {{ .Values.target.clusterName }}-{{ .Values.target.dc }}-default-sts-0 -- \
      /opt/cassandra/bin/cqlsh -u {{ .Values.target.clusterName }}-superuser \
      -p $(cat /secret-target/password) --execute "SELECT JSON * FROM cassandradiff.$table;" > /results/cassandra-diff/$table.txt 2>/dev/null;
    }
    collect "job_results"
    collect "job_start_index"
    collect "job_summary"
    collect "keyspace_index"
    collect "mismatches"
    collect "partition_errors"
    collect "running_jobs"
    collect "source_cluster_index"
    collect "target_cluster_index"
    collect "task_errors"
  localconfig.yaml: |
    splits: {{ .Values.cassandra_diff_config.splits }}
    buckets: {{ .Values.cassandra_diff_config.buckets }}
    rate_limit: {{ .Values.cassandra_diff_config.rate_limit }}
    token_scan_fetch_size: {{ .Values.cassandra_diff_config.token_scan_fetch_size }}
    partition_read_fetch_size: {{ .Values.cassandra_diff_config.partition_read_fetch_size }}
    read_timeout_millis: {{ .Values.cassandra_diff_config.read_timeout_millis }}
    reverse_read_probability: {{ .Values.cassandra_diff_config.reverse_read_probability }}
    consistency_level: {{ .Values.cassandra_diff_config.consistency_level }}
    metadata_options:
      keyspace: {{ .Values.cassandra_diff_config.metadata_options.keyspace }}
      replication: "{{ .Values.cassandra_diff_config.metadata_options.replication }}"
      ttl: {{ int .Values.cassandra_diff_config.metadata_options.ttl }}
      should_init: {{ .Values.cassandra_diff_config.metadata_options.should_init }}
    cluster_config:
      source:
        impl: "org.apache.cassandra.diff.ContactPointsClusterProvider"
        name: "{{ .Values.source.clusterName }}"
        contact_points: "{{ .Values.source.clusterName }}-{{ .Values.source.dc }}-service"
        port: "9042"
        dc: "{{ .Values.source.dc }}"
      target:
        impl: "org.apache.cassandra.diff.ContactPointsClusterProvider"
        name: "{{ .Values.target.clusterName }}"
        contact_points: "{{ .Values.target.clusterName }}-{{ .Values.target.dc }}-service"
        port: "9042"
        dc: "{{ .Values.target.dc }}"
      metadata:
        impl: "org.apache.cassandra.diff.ContactPointsClusterProvider"
        name: "{{ .Values.target.clusterName }}"
        contact_points: "{{ .Values.target.clusterName }}-{{ .Values.target.dc }}-service"
        port: "9042"
        dc: "dc2"