apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cassandra-mgmt-image
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  templates:
  - name: cassandra-mgmt-image-template
    inputs:
      parameters:
      - name: registry_ip
    container:
      image: gcr.io/kaniko-project/executor:v1.0.0
      args:
      - --dockerfile=/generated/Dockerfile
      - --context=dir:///build
      - {{`--destination={{inputs.parameters.registry_ip}}:30000/adelphi/management-api-for-apache-cassandra`}}
      - --insecure=true
      volumeMounts:
        - name: build
          mountPath: /build
        - name: generated
          mountPath: /generated
    initContainers:
    - name: generate-dockerfile
      image: alpine
      command:
        - sh
        - -c
      args:
        - echo "FROM {{`{{inputs.parameters.registry_ip}}`}}:30000/adelphi/cassandra" | cat - /configmap/Dockerfile > /generated/Dockerfile
      volumeMounts:
      - name: generated
        mountPath: /generated
      - name: configmap
        mountPath: /configmap
    - name: clone-cassandra-mgmt-api
      image: alpine/git
      workingDir: /build
      command:
        - sh
        - -c
      args:
        - git clone https://github.com/datastax/management-api-for-apache-cassandra .;
          git checkout v0.1.13;
          cp /configmap/docker-entrypoint.sh /build;
      volumeMounts:
      - name: build
        mountPath: /build
      - name: configmap
        mountPath: /configmap
    - name: build-cassandra-mgmt-api
      image: maven:3-openjdk-11
      workingDir: /build
      args:
        - mvn
        - clean
        - package
        - -DskipTests
      volumeMounts:
      - name: build
        mountPath: /build
    volumes:
    - name: build
      emptyDir: {}
    - name: generated
      emptyDir: {}
    - name: configmap
      configMap:
        name: cassandra-mgmt-dockerfile-configmap