apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cassandra-mgmt-image
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  templates:
  - name: cassandra-mgmt-image-template
    container:
      image: gcr.io/kaniko-project/executor:v1.6.0-debug
      command:
        - sh
        - -c
      args:
      - until `wget --spider http://localhost:30000`; do echo sleep && sleep 1; done;
        /kaniko/executor --dockerfile=/configmap/Dockerfile
        --context=dir:///build
        --destination=localhost:30000/adelphi/management-api-for-apache-cassandra
        --insecure=true;
      volumeMounts:
        - name: build
          mountPath: /build
        - name: configmap
          mountPath: /configmap
    sidecars:
    - name : nginx
      image: nginx
      ports:
        - containerPort: 30000
          hostPort: 30000
          protocol: TCP
      volumeMounts:
      - name: proxy-config
        mountPath: /etc/nginx/conf.d
    initContainers:
    - name: clone-cassandra-mgmt-api
      image: alpine/git
      workingDir: /build
      command:
        - sh
        - -c
      args:
        - git clone https://github.com/datastax/management-api-for-apache-cassandra .;
          git checkout v0.1.27;
      volumeMounts:
      - name: build
        mountPath: /build
    volumes:
    - name: build
      emptyDir: {}
    - name: generated
      emptyDir: {}
    - name: configmap
      configMap:
        name: cassandra-mgmt-dockerfile-configmap
    - name: proxy-config
      configMap:
        name: registry-proxy-configmap