apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cassandra-mgmt-image
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  templates:
  - name: cassandra-mgmt-image-template
    inputs:
      parameters:
      - name: registry_ip
    container:
      image: gcr.io/kaniko-project/executor:v1.0.0
      args:
      - --dockerfile=/configmap/Dockerfile
      - --context=dir:///build
      - {{`--destination={{inputs.parameters.registry_ip}}:30000/adelphi/management-api-for-apache-cassandra`}}
      - --insecure=true
      - --build-arg=REGISTRY={{`{{inputs.parameters.registry_ip}}`}}
      volumeMounts:
        - name: build
          mountPath: /build
        - name: configmap
          mountPath: /configmap
    initContainers:
    - name: clone-cassandra-mgmt-api
      image: alpine/git
      workingDir: /build
      command:
        - sh
        - -c
      args:
        - git clone https://github.com/datastax/management-api-for-apache-cassandra .;
          git checkout v0.1.25;
          cp /configmap/docker-entrypoint.sh scripts/docker-entrypoint.sh;
      volumeMounts:
      - name: build
        mountPath: /build
      - name: configmap
        mountPath: /configmap
    volumes:
    - name: build
      emptyDir: {}
    - name: generated
      emptyDir: {}
    - name: configmap
      configMap:
        name: cassandra-mgmt-dockerfile-configmap