apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gemini-job
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  templates:
  - name: gemini-oracle-sut
    container:
      image: golang
      workingDir: /workspace
      command:
        - sh
        - -c
      args:
        - /workspace/gemini
          --oracle-cluster={{ .Values.source.clusterName }}-{{ .Values.source.dc }}-service
          --oracle-username={{ .Values.source.clusterName }}-superuser
          --oracle-password="`cat /source-secret/password`"
          --test-cluster={{ .Values.target.clusterName }}-{{ .Values.target.dc }}-service
          --test-username={{ .Values.target.clusterName }}-superuser
          --test-password="`cat /target-secret/password`"
          --duration=1m
          --outfile=/results/gemini/results.txt
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: source-secret-volume
        mountPath: /source-secret
        readOnly: true
      - name: target-secret-volume
        mountPath: /target-secret
        readOnly: true
      - name: results
        mountPath: /results
    initContainers:
    - name: download-gemini
      image: alpine
      command: ["sh", "-c"]
      workingDir: /workspace
      args:
        - wget -O - {{ .Values.gemini_download_url }} | tar -zxvf -
      volumeMounts:
      - name: workspace
        mountPath: /workspace
    volumes:
    - name: workspace
      emptyDir: {}
    - name: source-secret-volume
      secret:
        secretName: {{ .Values.source.clusterName }}-superuser
        items:
        - key: password
          path: password
    - name: target-secret-volume
      secret:
        secretName: {{ .Values.target.clusterName }}-superuser
        items:
        - key: password
          path: password
    - name: results
      persistentVolumeClaim:
        claimName: results-pvc