kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000