apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: {{ .Values.namespace }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: prometheus-svc.{{ .Values.namespace }}.svc.cluster.local:9090
        basicAuth: false
        editable: true
  dashboard.yaml: |
    apiVersion: 1
    providers:
      - name: 'NoSQLBench'
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: false
        options:
          path: /dashboards/nb4-new-dashboard.json
          foldersFromFilesStructure: false
  nb4-new-dashboard.json:
    {{ .Files.Get "config/grafana/nb4-new-dashboard.json" | toPrettyJson }}