kind: Service
apiVersion: v1
metadata:
  name: graphite-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: graphite-exporter
  ports:
  - name: http
    port: 9108
    targetPort: 9108
  - name: udp
    port: 9109
    targetPort: 9109