apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /results
            name: results
      volumes:
        - name: results
          persistentVolumeClaim:
            claimName: nfs-pvc