apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nosqlbench-job
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  templates:
  - name: nosqlbench-source
    container:
      image: nosqlbench/nosqlbench:latest
      args: [
        "--show-stacktraces",
        "--report-csv-to=/results",
        "--report-graphite-to=graphite-service:9109",
        "/workspace/nosqlbench_source.yaml",
        "source",
        "scenarioname=source",
        "hosts={{ .Values.source.clusterName }}-{{ .Values.source.dc }}-service",
        "username={{ .Values.source.clusterName }}-superuser",
        "passfile=/secret/password"
      ]
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: secret-volume
        mountPath: /secret
        readOnly: true
      - name: results-pv
        mountPath: /results
    initContainers:
    - name: extract-config
      image: registry:5000/adelphi:0.2.0
      command: ["sh", "-c", "-e"]
      args:
        - echo "Create nosqlbench config using adelphi tool";
          adelphi --hosts="{{ .Values.source.clusterName }}-{{ .Values.source.dc }}-service" --username="{{ .Values.source.clusterName }}-superuser" --password="`cat /secret/password`" --keyspaces="{{ .Values.gemini_schema_keyspace }}" --no-anonymize export-nb > /workspace/nosqlbench_source.yaml;
          echo "Done";
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: secret-volume
        mountPath: /secret
        readOnly: true
    volumes:
    - name: workspace
      emptyDir: {}
    - name: secret-volume
      secret:
        secretName: {{ .Values.source.clusterName }}-superuser
        items:
        - key: password
          path: password
    - name: results-pv
      persistentVolumeClaim:
        claimName: nosqlbench-source-pvc
  - name: nosqlbench-target
    container:
      image: nosqlbench/nosqlbench:latest
      args: [
        "--show-stacktraces",
        "--report-csv-to=/results",
        "--report-graphite-to=graphite-service:9109",
        "/workspace/nosqlbench_target.yaml",
        "target",
        "scenarioname=target",
        "hosts={{ .Values.target.clusterName }}-{{ .Values.target.dc }}-service",
        "username={{ .Values.target.clusterName }}-superuser",
        "passfile=/secret/password"
      ]
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: secret-volume
        mountPath: /secret
        readOnly: true
      - name: results-pv
        mountPath: /results
    initContainers:
    - name: extract-config
      image: registry:5000/adelphi:0.2.0
      command: ["sh", "-c", "-e"]
      args:
        - echo "Create nosqlbench config using adelphi tool";
          adelphi --hosts="{{ .Values.target.clusterName }}-{{ .Values.target.dc }}-service" --username="{{ .Values.target.clusterName }}-superuser" --password="`cat /secret/password`" --keyspaces="{{ .Values.gemini_schema_keyspace }}" --no-anonymize export-nb > /workspace/nosqlbench_target.yaml;
          echo "Done";
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: secret-volume
        mountPath: /secret
        readOnly: true
    volumes:
    - name: workspace
      emptyDir: {}
    - name: secret-volume
      secret:
        secretName: {{ .Values.target.clusterName }}-superuser
        items:
        - key: password
          path: password
    - name: results-pv
      persistentVolumeClaim:
        claimName: nosqlbench-target-pvc