apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: registry
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  templates:
  - name: registry-template
    metadata:
      labels:
        app: docker-registry
    daemon: true
    container:
      image: registry:2.6.2
      env:
        - name: REGISTRY_HTTP_ADDR
          value: ":30000"
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: "/var/lib/registry"
      ports:
      - name: http
        containerPort: 30000
      volumeMounts:
      - name: image-store
        mountPath: "/var/lib/registry"
    volumes:
    - name: image-store
      emptyDir: {}
