apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-proxy-configmap
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    client_max_body_size 1000M;
    server {
      listen        30000;
      location / {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
        proxy_pass         "http://docker-registry.{{ .Values.namespace }}:30000/";
      }
    }