apiVersion: v1
kind: ConfigMap
metadata:
  name: results-server-configmap
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
      listen        8080;
      location / {
        autoindex on;
        root  /results;
      }
      location /api/ {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
        proxy_pass         "http://127.0.0.1:8181/api/";
      }
    }