apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi