kind: Service
apiVersion: v1
metadata:
  name: results
  namespace: {{ .Values.namespace }}
  labels:
    app: results
spec:
  selector:
    app: results
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080