apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: results
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  templates:
  - name: results-server
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: results-server
          namespace: {{ .Values.namespace }}
          ownerReferences:
          - apiVersion: argoproj.io/v1alpha1
            blockOwnerDeletion: true
            kind: Workflow
            name: "{{`{{workflow.name}}`}}"
            uid: "{{`{{workflow.uid}}`}}"
        spec:
          containers:
          - name : nginx
            image: nginx
            volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
            - name: gemini
              mountPath: /results/gemini
            - name: nosqlbench-source
              mountPath: /results/nosqlbench-source
            - name: nosqlbench-target
              mountPath: /results/nosqlbench-target
            - name: cassandra-diff
              mountPath: /results/cassandra-diff
          - name : node
            image: adelphitools/adelphi-api:0.0.1
            env:
            - name: DATA_PATH
              value: "/results"
            - name: PORT
              value: "8181"
            volumeMounts:
            - name: gemini
              mountPath: /results/gemini
            - name: nosqlbench-source
              mountPath: /results/nosqlbench-source
            - name: nosqlbench-target
              mountPath: /results/nosqlbench-target
            - name: cassandra-diff
              mountPath: /results/cassandra-diff
          volumes:
          - name: config
            configMap:
              name: results-server-configmap
          - name: gemini
            persistentVolumeClaim:
              claimName: gemini-pvc
          - name: nosqlbench-source
            persistentVolumeClaim:
              claimName: nosqlbench-source-pvc
          - name: nosqlbench-target
            persistentVolumeClaim:
              claimName: nosqlbench-target-pvc
          - name: cassandra-diff
            persistentVolumeClaim:
              claimName: cassandra-diff-pvc