apiVersion: v1
kind: PersistentVolume
metadata:
  name: results-pv
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  {{- toYaml .Values.results_volume_spec | nindent 2 }}