apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 100Mi