apiVersion: v1
kind: Pod
metadata:
  name: results-server
  namespace: {{ .Values.namespace }}
spec:
  containers:
    - name: results
      image: nginx
      volumeMounts:
      - name: config
        mountPath: /etc/nginx/conf.d
      - name: results-pv
        mountPath: /results
  initContainers:
  - name: clear-index
    image: alpine
    command:
      - sh
      - -c
    args:
      # remove sample index created by the NFS server
      - rm /results/index.html
    volumeMounts:
    - name: results-pv
      mountPath: /results
  volumes:
  - name: config
    configMap:
      name: results-server-configmap
  - name: results-pv
    persistentVolumeClaim:
      claimName: results-pvc