apiVersion: v1
kind: Pod
metadata:
  name: results-server
  namespace: {{ .Values.namespace }}
spec:
  containers:
    - name: results
      image: nginx
      volumeMounts:
      - name: config
        mountPath: /etc/nginx/conf.d
      - name: results
        mountPath: /results
  volumes:
  - name: config
    configMap:
      name: results-server-configmap
  - name: results
    persistentVolumeClaim:
      claimName: results-pvc