apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-target-configmap
  namespace: {{ .Values.namespace }}
data:
  schema.cql: |-
{{ default .Values.cql_schema .Values.target.cql_schema | indent 4}}