namespace: cass-operator
clusterSize: 1 # number of nodes per cluster
allowMultipleNodesPerWorker: false

storageClassName: local-path

source:
  dc: dc1
  clusterName: source
  version: "3.11.7"

target:
  dc: dc2
  clusterName: target
  version: "4.0.0"
  git_identifier:

gemini_test_duration: 1m

cassandra_diff_config:
  # This is how many parts we split the full token range in.
  # Each of these splits is then compared between the clusters
  splits: 10000

  # Number of buckets - splits / buckets should be under 100k to avoid wide partitions when storing the metadata
  buckets: 100

  # global rate limit - this is how many q/s you think the target clusters can handle
  rate_limit: 10000

  # Fetch size to use for the query fetching the tokens in the cluster
  token_scan_fetch_size: 1000
  # Fetch size to use for the queries fetching the rows of each partition
  partition_read_fetch_size: 1000

  read_timeout_millis: 10000
  reverse_read_probability: 0.5
  consistency_level: ALL
  metadata_options:
    keyspace: cassandradiff
    replication: "{'class':'SimpleStrategy', 'replication_factor':'1'}"
    ttl: 31536000
    should_init: true

cql_schema: |-
  CREATE KEYSPACE IF NOT EXISTS testkeyspace
    WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}
    AND durable_writes = true;

  CREATE TABLE IF NOT EXISTS testkeyspace.testtable (
    key text,
    value text,
    PRIMARY KEY (key)
  );
gemini_schema_keyspace: testkeyspace
